version: '3.8'
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/database
    container_name: database
    environment:
      POSTGRES_USER: postgresprod
      POSTGRES_PASSWORD: adminprod
      POSTGRES_DB: databasenameprod
    ports:
      - 5433:5432
    networks:
      - myapplication

  backend:
    image: backend
    container_name: backend
    build: ./backend
    environment:
      DB_SERVER: database
    ports:
      - 8081:8080
    networks:
      - myapplication
    depends_on:
      - postgres

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    environment:
      VITE_BACKEND_SERVER: http://localhost:8081
    ports:
      - 5173:5173
    networks:
      - myapplication

volumes:
  postgres:
    driver: local 
    
networks:
    myapplication:
      driver: bridge



